### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by litencatt** [litencatt/samplar#1]
### ver 0.1.0
- [x] Implement test 
- [ ] Support Hash params
- [ ] Support keyword args
- [ ] Show each client method list

### Later ...
- [ ] Set default params to form
- [ ] Labeling function
- [ ] Set notes to each methods
- [ ] Generate method list with min yaml configuration
    - Configure only client name

**Comment by litencatt** [comment]
## The actual of client model calling examples
create instance and call methods
- `Foo::Client.post(bar, buz)`
- `Foo::Client.new.post(bar, buz)`
